# Generated by Django 3.2.8 on 2021-12-02 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_usu', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, verbose_name='Nombre')),
                ('lastName', models.CharField(max_length=40, verbose_name='Apellidos')),
                ('document', models.IntegerField(verbose_name='Documento')),
                ('email', models.CharField(max_length=100, unique=True, verbose_name='Email')),
                ('password', models.CharField(max_length=256, verbose_name='clave')),
                ('cellphone', models.CharField(max_length=25, verbose_name='Telefono')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ord_detail', models.BigIntegerField(verbose_name='order_detail')),
                ('amount_prod', models.IntegerField(verbose_name='Amount Product')),
                ('id_prod', models.IntegerField(verbose_name='Id Product')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_detail_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('send_type', models.CharField(max_length=100, verbose_name='Tipo envio')),
                ('send_price', models.CharField(max_length=100, verbose_name='Gasto envio')),
                ('total_charge', models.IntegerField(verbose_name='Cargo total')),
                ('order_status', models.CharField(max_length=100, verbose_name='Estado orden')),
                ('pay', models.IntegerField(verbose_name='Pago')),
                ('pay_type', models.CharField(max_length=100, verbose_name='Tipo pago')),
                ('order_detail', models.IntegerField(verbose_name='Id Detalle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
